name: 'env0 - Run Terratag'
description: 'Sets up and runs Terratag CLI in your GitHub Actions workflow.'
author: 'env0, Inc.'
inputs:
  cli_args:
    description: 'The arguments to pass to terratag cli.'
    required: true
  terratag_version:
    description: 'Terratag version to use.'
    required: false
    default: 'latest'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'terminal'
  color: 'purple'
