name: 'env0 - Run Terratag'
description: 'Sets up and runs Terratag CLI in your GitHub Actions workflow.'
author: 'env0, Inc.'
inputs:
  tags:
    description: 'Strigified JSON object of the tags to add'
    required: true
  dir:
    description: 'directory to run terratag in'
    required: false
  skipTerratagFiles:
    description: 'Should .terratag.tf be skipped (specify "true" or "false" as value, default is "true")'
    required: false
  verbose:
    description: 'Specify "true" for verbose output'
    required: false
  rename:
    description: 'Specify "false" to keep original .tf filenames'
    required: false
  terratagVersion:
    description: 'Terratag version to use.'
    required: false
    default: 'latest'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'terminal'
  color: 'purple'
